import { defineDataModel } from "./define-model.ts";
import { JURISDICTION_ISO_3166_2_CODES } from "./jurisdiction-iso-3166-2.ts";

const commonProps = {
  name: {
    label: "Name",
    types: ["string"],
    required: true,
    multiplicity: "many",
    description: "Primary display name for the entity.",
    examples: ["Jane Example"],
    frontend: "primary",
  },
  aliases: {
    label: "Aliases",
    types: ["string"],
    multiplicity: "many",
    description: "Alternative names, spellings, or aliases exposed by the source.",
    examples: ["J. Example", "Example Jane"],
    frontend: "primary",
  },
  notes: {
    label: "Notes",
    types: ["string"],
    multiplicity: "many",
    description: "Short explanatory note shown near the entity body.",
    examples: ["Matched by full name and date of birth."],
    frontend: "primary",
  },
} as const;

export const dataModelV002 = defineDataModel({
  version: "0.0.2",
  title: "OpenRisk Data Model",
  description:
    "Frontend-compatible v1 entity array contract for single-file OpenRisk TypeScript plugins.",
  typedValues: {
    string: {
      label: "String",
      jsonType: "string",
      description: "Plain text value.",
      detail: "Use for names, identifiers, labels, short descriptions, and source-provided text.",
      examples: ["Jane Example", "active"],
    },
    number: {
      label: "Number",
      jsonType: "number",
      description: "JSON number.",
      detail: "Use for numeric scores, counters, monetary amounts already normalized as numbers, or credit values.",
      examples: [42, 0.87],
    },
    boolean: {
      label: "Boolean",
      jsonType: "boolean",
      description: "True or false flag.",
      detail: "Use for binary facts such as PEP status, sanction status, or adverse activity detection.",
      examples: [true, false],
    },
    "jurisdiction-iso-3166-2": {
      label: "Jurisdiction (ISO 3166-2)",
      jsonType: "string",
      description: "OpenCorporates-style jurisdiction code derived from ISO 3166-2.",
      detail:
        "Use for registry jurisdictions such as gb, sk, us_de, or ca_bc. This is not interchangeable with country.",
      examples: ["sk", "us_de"],
      allowedValues: JURISDICTION_ISO_3166_2_CODES,
    },
    "date-iso8601": {
      label: "ISO Date",
      jsonType: "string",
      description: "Full ISO date.",
      detail: "Use when the source provides a complete calendar date in YYYY-MM-DD form.",
      examples: ["2024-06-01"],
    },
    "date-partial-iso8601": {
      label: "Partial ISO Date",
      jsonType: "string",
      description: "Partial ISO date.",
      detail: "Use when the source only provides a year or year-month value.",
      examples: ["2024", "2024-06"],
    },
    "date-time-iso8601": {
      label: "ISO Date-Time",
      jsonType: "string",
      description: "Full ISO timestamp.",
      detail: "Use for retrieved-at, updated-at, or event timestamps when time is known.",
      examples: ["2024-06-01T12:34:56Z"],
    },
    url: {
      label: "URL",
      jsonType: "string",
      description: "Source or profile URL.",
      detail: "Use for links the user can open directly from the OpenRisk result view.",
      examples: ["https://example.com/profile/jane"],
    },
    address: {
      label: "Address",
      jsonType: "string",
      description: "Human-readable address.",
      detail: "Use for postal addresses and source-provided location strings that should render as addresses.",
      examples: ["Main Street 1, Bratislava"],
    },
    "location-iso6709": {
      label: "ISO 6709 Location",
      jsonType: "string",
      description: "Geographic coordinate string.",
      detail: "Reserved for coordinate values following ISO 6709-style location encoding.",
      examples: ["+48.1486+017.1077/"],
    },
    "image-url": {
      label: "Image URL",
      jsonType: "string",
      description: "URL to an image.",
      detail: "Use for externally hosted profile images or logos.",
      examples: ["https://example.com/avatar.jpg"],
    },
    "image-base64": {
      label: "Base64 Image",
      jsonType: "string",
      description: "Base64 encoded image payload.",
      detail: "Use sparingly for embedded images when a URL is not available.",
      examples: ["data:image/png;base64,..."],
    },
    "key-value": {
      label: "Key Value",
      jsonType: "object",
      description: "Labeled extra value.",
      detail: "Used inside $extra to preserve source-specific fields without promoting them into canonical props.",
      examples: [{ key: "Dataset", value: "pep" }],
    },
  },
  entities: {
    "entity.person": {
      id: "entity.person",
      label: "Person",
      icon: "user",
      group: "Identity",
      description: "A physical person.",
      usage: "Use for PEP, sanctions, officer, ownership, registry, or extracted person records.",
      frontend: "primary",
      props: {
        ...commonProps,
        birthDate: {
          label: "Birth Date",
          types: ["date-iso8601", "date-partial-iso8601", "date-time-iso8601"],
          multiplicity: "many",
          description: "Birth date as provided by the source.",
          examples: ["1980-05-14", "1980"],
          frontend: "primary",
        },
        birthPlace: {
          label: "Birth Place",
          types: ["string"],
          multiplicity: "many",
          description: "Birth location text.",
          examples: ["Bratislava"],
          frontend: "primary",
        },
        nationalities: {
          label: "Nationalities",
          types: ["string"],
          multiplicity: "many",
          description: "Nationality or citizenship labels.",
          examples: ["Slovakia"],
          frontend: "primary",
        },
        jurisdiction: {
          label: "Jurisdiction",
          types: ["jurisdiction-iso-3166-2"],
          multiplicity: "many",
          description: "Registry or legal jurisdiction associated with the person record.",
          examples: ["sk", "us_de"],
          frontend: "primary",
        },
        addresses: {
          label: "Addresses",
          types: ["address"],
          multiplicity: "many",
          description: "Known or source-provided addresses.",
          examples: ["Main Street 1, Bratislava"],
          frontend: "primary",
        },
        emails: {
          label: "Emails",
          types: ["string"],
          multiplicity: "many",
          description: "Email addresses associated with the person.",
          examples: ["jane@example.com"],
          frontend: "primary",
        },
        phones: {
          label: "Phones",
          types: ["string"],
          multiplicity: "many",
          description: "Phone numbers associated with the person.",
          examples: ["+421 900 000 000"],
          frontend: "primary",
        },
        pepStatus: {
          label: "PEP Status",
          types: ["boolean"],
          multiplicity: "one",
          description: "True when PEP exposure is confirmed; false when explicitly clear.",
          examples: [true],
          builderField: "isPep",
          frontend: "primary",
        },
        sanctioned: {
          label: "Sanctioned",
          types: ["boolean"],
          multiplicity: "one",
          description: "True when sanctions exposure is confirmed; false when explicitly clear.",
          examples: [false],
          builderField: "isSanctioned",
          frontend: "primary",
        },
      },
      examples: {
        minimal: { name: "Jane Example" },
        common: { name: "Jane Example", aliases: ["J. Example"], pepStatus: false, sanctioned: false },
        full: {
          name: "Jane Example",
          aliases: ["J. Example"],
          birthDate: "1980-05-14",
          birthPlace: "Bratislava",
          nationalities: ["Slovakia"],
          jurisdiction: ["sk"],
          addresses: ["Main Street 1, Bratislava"],
          emails: ["jane@example.com"],
          pepStatus: true,
          sanctioned: false,
        },
      },
    },
    "entity.organization": {
      id: "entity.organization",
      label: "Organization",
      icon: "building",
      group: "Identity",
      description: "A company, legal entity, public body, or other organization.",
      usage: "Use for company registry, sanctions legal entity, ownership, or related organization records.",
      frontend: "primary",
      props: {
        ...commonProps,
        previousNames: {
          label: "Previous Names",
          types: ["string"],
          multiplicity: "many",
          description: "Previous registered or known names.",
          examples: ["Example Trading s.r.o."],
          frontend: "primary",
        },
        registrationId: {
          label: "Registration ID",
          types: ["string"],
          multiplicity: "one",
          description: "Primary registry, company, ICO, EIN, or comparable identifier.",
          examples: ["12345678"],
          frontend: "primary",
        },
        country: {
          label: "Country",
          types: ["string"],
          multiplicity: "many",
          description: "Country label or code associated with the organization.",
          examples: ["SK"],
          frontend: "primary",
        },
        jurisdiction: {
          label: "Jurisdiction",
          types: ["jurisdiction-iso-3166-2"],
          multiplicity: "many",
          description: "Registry or legal jurisdiction associated with the organization.",
          examples: ["sk", "us_de"],
          frontend: "primary",
        },
        address: {
          label: "Address",
          types: ["address"],
          multiplicity: "one",
          description: "Primary address for the organization.",
          examples: ["Main Street 1, Bratislava"],
          frontend: "primary",
        },
        status: {
          label: "Status",
          types: ["string"],
          multiplicity: "one",
          description: "Source-provided lifecycle status.",
          examples: ["active"],
          frontend: "primary",
        },
        involvedPersons: {
          label: "Involved Persons",
          types: ["string"],
          multiplicity: "many",
          description: "Flattened person relationships such as officers or statutory bodies.",
          examples: ["Jane Example, director"],
          frontend: "primary",
        },
        legalRoles: {
          label: "Legal Roles",
          types: ["string"],
          multiplicity: "many",
          description: "Legal role labels or classification labels.",
          examples: ["Director"],
          frontend: "primary",
        },
        sourceRegister: {
          label: "Source Register",
          types: ["string"],
          multiplicity: "one",
          description: "Registry name or source register identifier.",
          examples: ["ORSR"],
          frontend: "primary",
        },
        entryTypes: {
          label: "Entry Types",
          types: ["string"],
          multiplicity: "many",
          description: "Source-specific entry type labels.",
          examples: ["statutory_body"],
          frontend: "primary",
        },
        effectiveTo: {
          label: "Effective To",
          types: ["date-iso8601", "date-partial-iso8601", "date-time-iso8601"],
          multiplicity: "one",
          description: "End date for a registry status or relation.",
          examples: ["2025-01-31"],
          frontend: "primary",
        },
        pepStatus: {
          label: "PEP Status",
          types: ["boolean"],
          multiplicity: "one",
          description: "True when PEP exposure is associated with the organization.",
          examples: [false],
          builderField: "isPep",
          frontend: "primary",
        },
        sanctioned: {
          label: "Sanctioned",
          types: ["boolean"],
          multiplicity: "one",
          description: "True when sanctions exposure is associated with the organization.",
          examples: [true],
          builderField: "isSanctioned",
          frontend: "primary",
        },
      },
      examples: {
        minimal: { name: "Example Ltd" },
        common: {
          name: "Example Ltd",
          registrationId: "12345678",
          country: "SK",
          jurisdiction: "sk",
          status: "active",
        },
        full: {
          name: "Example Ltd",
          aliases: ["Example Group"],
          previousNames: ["Example Trading"],
          registrationId: "12345678",
          country: "SK",
          jurisdiction: "sk",
          address: "Main Street 1, Bratislava",
          status: "active",
          involvedPersons: ["Jane Example, director"],
          sanctioned: false,
        },
      },
    },
    "entity.mediaMention": {
      id: "entity.mediaMention",
      label: "Media Mention",
      icon: "newspaper",
      group: "Media",
      description: "One analyzed media article, search result, or URL.",
      usage: "Use for adverse-media checks and URL analysis results.",
      frontend: "primary",
      props: {
        name: { ...commonProps.name, description: "Screened target name." },
        title: {
          label: "Title",
          types: ["string"],
          multiplicity: "one",
          description: "Article or page title.",
          examples: ["Example article"],
          frontend: "primary",
        },
        url: {
          label: "URL",
          types: ["url"],
          multiplicity: "one",
          description: "Article or source URL.",
          examples: ["https://example.com/article"],
          frontend: "primary",
        },
        analysis: {
          label: "Analysis",
          types: ["string"],
          multiplicity: "one",
          description: "Concise human-readable analysis.",
          examples: ["No adverse activity found."],
          builderField: "analysisText",
          frontend: "primary",
        },
        adverseActivityDetected: {
          label: "Adverse Activity Detected",
          types: ["boolean"],
          multiplicity: "one",
          description: "Whether the article indicates adverse activity.",
          examples: [false],
          frontend: "primary",
        },
        Claim: {
          label: "Claim",
          types: ["key-value"],
          multiplicity: "many",
          description: "Atomic fact claim stored in $extra with key Claim.",
          examples: ["The article mentions Jane Example."],
          builderField: "claims",
          frontend: "extra",
          notes: "In v0.0.2 the OpenRisk media mention card reads claims from $extra, not $props.",
        },
      },
      examples: {
        minimal: { name: "Jane Example", title: "Example article" },
        common: {
          name: "Jane Example",
          title: "Example article",
          url: "https://example.com/article",
          adverseActivityDetected: false,
        },
        full: {
          name: "Jane Example",
          title: "Example article",
          url: "https://example.com/article",
          analysis: "No adverse activity found.",
          adverseActivityDetected: false,
          Claim: ["The article mentions Jane Example."],
        },
      },
    },
    "entity.riskTopic": {
      id: "entity.riskTopic",
      label: "Risk Topic",
      icon: "radar",
      group: "Screening",
      description: "One topic-level screening result from adverse-media analysis.",
      usage: "Use one entity per risk topic so OpenRisk can group the report into a single summary card.",
      frontend: "primary",
      props: {
        name: { ...commonProps.name, description: "Screened target name." },
        topicId: {
          label: "Topic ID",
          types: ["string"],
          multiplicity: "one",
          description: "Stable topic identifier such as corruption or financial_crime.",
          examples: ["corruption"],
          frontend: "primary",
        },
        summary: {
          label: "Summary",
          types: ["string"],
          multiplicity: "one",
          description: "Topic-specific screening summary.",
          examples: ["No corruption-related adverse activity found."],
          frontend: "primary",
        },
        adverseActivityDetected: {
          label: "Adverse Activity Detected",
          types: ["boolean"],
          multiplicity: "one",
          description: "Whether the topic contains adverse findings.",
          examples: [false],
          frontend: "primary",
        },
      },
      examples: {
        minimal: { name: "Jane Example", topicId: "corruption" },
        common: { name: "Jane Example", topicId: "corruption", adverseActivityDetected: false },
        full: {
          name: "Jane Example",
          topicId: "corruption",
          summary: "No corruption-related adverse activity found.",
          adverseActivityDetected: false,
        },
      },
    },
    "entity.socialProfile": {
      id: "entity.socialProfile",
      label: "Social Profile",
      icon: "at-sign",
      group: "Media",
      description: "One discovered public social media profile.",
      usage: "Use for social discovery results tied to a screened target.",
      frontend: "primary",
      props: {
        name: { ...commonProps.name, description: "Screened target name." },
        platform: {
          label: "Platform",
          types: ["string"],
          multiplicity: "one",
          description: "Social network or platform name.",
          examples: ["LinkedIn"],
          frontend: "primary",
        },
        profileTitle: {
          label: "Profile Title",
          types: ["string"],
          multiplicity: "one",
          description: "Profile display title.",
          examples: ["Jane Example - CEO"],
          frontend: "primary",
        },
        profileUrl: {
          label: "Profile URL",
          types: ["url"],
          multiplicity: "one",
          description: "Public profile URL.",
          examples: ["https://linkedin.com/in/jane-example"],
          frontend: "primary",
        },
        userId: {
          label: "User ID",
          types: ["string"],
          multiplicity: "one",
          description: "Platform-specific user ID or handle.",
          examples: ["jane-example"],
          frontend: "primary",
        },
      },
      examples: {
        minimal: { name: "Jane Example", platform: "LinkedIn" },
        common: { name: "Jane Example", platform: "LinkedIn", profileUrl: "https://linkedin.com/in/jane-example" },
        full: {
          name: "Jane Example",
          platform: "LinkedIn",
          profileTitle: "Jane Example - CEO",
          profileUrl: "https://linkedin.com/in/jane-example",
          userId: "jane-example",
        },
      },
    },
    "entity.financialRecord": {
      id: "entity.financialRecord",
      label: "Financial Record",
      icon: "receipt",
      group: "Screening",
      description: "One financial obligation, debt, or payment-related record.",
      usage: "Use for debtor lists and similar financial-screening outputs.",
      frontend: "primary",
      props: {
        name: { ...commonProps.name, description: "Debtor, payer, beneficiary, or subject name." },
        amountOwed: {
          label: "Amount Owed",
          types: ["string"],
          multiplicity: "one",
          description: "Source-formatted amount owed.",
          examples: ["123.45 EUR"],
          frontend: "primary",
        },
        location: {
          label: "Location",
          types: ["address"],
          multiplicity: "one",
          description: "Address or location associated with the record.",
          examples: ["Main Street 1, Bratislava"],
          frontend: "primary",
        },
        debtSource: {
          label: "Debt Source",
          types: ["string"],
          multiplicity: "one",
          description: "Source registry or authority for the record.",
          examples: ["SK_TAX"],
          frontend: "primary",
        },
      },
      examples: {
        minimal: { name: "Jane Example" },
        common: { name: "Jane Example", amountOwed: "123.45 EUR", debtSource: "SK_TAX" },
        full: {
          name: "Jane Example",
          amountOwed: "123.45 EUR",
          location: "Main Street 1, Bratislava",
          debtSource: "SK_TAX",
        },
      },
    },
    "entity.detectedEntity": {
      id: "entity.detectedEntity",
      label: "Detected Entity",
      icon: "spark",
      group: "Operations",
      description: "A discovered entity when person or organization type is not guaranteed.",
      usage: "Use for entity-recognition outputs and loose extraction results.",
      frontend: "generic",
      props: {
        name: commonProps.name,
        description: {
          label: "Description",
          types: ["string"],
          multiplicity: "one",
          description: "Short explanation of the detected entity.",
          examples: ["Mentioned as a related person in the article."],
          frontend: "properties",
        },
      },
      examples: {
        minimal: { name: "Jane Example" },
        common: { name: "Jane Example", description: "Related person detected in source text." },
        full: { name: "Jane Example", description: "Related person detected in source text." },
      },
    },
  },
});

export default dataModelV002;
